### ISSUE TITLE
Reference Implementation

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj-typeable#1]
A reference implementation:
https://gist.github.com/clinuxrulz/b20a2281a02c356360c7da66debaa61e

It does not need to be exactly the same. It just shows one way it can be possible.

I'd probably define a `class Invariant f => InvariantTypeable f` and `class Contravariant => ContravariantTypeable f` for convenience. (Allowing people to use `Typeable` for their own invariant and contravariant functors. )

**Comment by clinuxrulz** [comment]
In the above reference implementation, the data structures are represented first with products, coproducts and primatives only, then an invariant map `invmap` is applied to the typeable to make it a typeable for your data type (`Typeable<YourDataType> typeable = [some typeable decl].invmap(f,g);`)

**Comment by DanielGronau** [comment]
Wow, that looks impressive. I'll probably need some time to grok it :-)

**Comment by clinuxrulz** [comment]
Reference Implementation now out of date. Using a Free Invariant Functor pattern has simplified things drastically.
